services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cygree
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbadmin -d cygree"]
      interval: 5s
      timeout: 5s
      retries: 5
