# Generated by Django 5.1.2 on 2024-10-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Agent', 'Agent')], default='Client', max_length=100),
        ),
    ]
